# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-22 00:08
from __future__ import unicode_literals

from django.apps import apps
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


def copy_field(apps, schema_editor):
    AnswerPage = apps.get_model('ask_cfpb', 'AnswerPage')
    for page in AnswerPage.objects.all():
        for category in page.answer_base.category.all():
            page.category.add(category)
        for subcategory in page.answer_base.subcategory.all():
            page.subcategory.add(subcategory)

        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0016_modify_help_text_social_sharing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerpage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='answerpage',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='answerpage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='answerpage',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='Categorize this answer. Avoid putting into more than one category.', to='ask_cfpb.Category'),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Check to make this one of two featured answers on the landing page.'),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='featured_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='next_step',
            field=models.ForeignKey(blank=True, help_text="Formerly known as action items or upsell items.On the web page, these are labeled as 'Explore related resources.'", null=True, on_delete=django.db.models.deletion.CASCADE, to='ask_cfpb.NextStep'),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='search_tags_es',
            field=models.CharField(blank=True, help_text='Spanish search words or phrases, separated by commas', max_length=1000),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='statement',
            field=models.TextField(blank=True, help_text='(Optional) Use this field to rephrase the question title as a statement. Use only if this answer has been chosen to appear on a money topic portal (e.g. /consumer-tools/debt-collection).'),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='subcategory',
            field=models.ManyToManyField(blank=True, help_text='Choose only subcategories that belong to one of the categories checked above.', to='ask_cfpb.SubCategory'),
        ),
        migrations.AlterField(
            model_name='answerpage',
            name='answer',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answerpage',
            name='question',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answerpage',
            name='snippet',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Optional answer intro'),
        ),
        migrations.RunPython(copy_field),
    ]
