# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 01:21
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0016_modify_help_text_social_sharing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerpage',
            name='answer',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answerpage',
            name='question',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answerpage',
            name='snippet',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Optional answer intro'),
        ),
    ]
