# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 22:23
from __future__ import unicode_literals

from django.db import migrations
import v1.atomic_elements.organisms
import v1.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0017_open_editing_fields_on_answer_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerpage',
            name='answer',
            field=wagtail.wagtailcore.fields.StreamField([('text', wagtail.wagtailcore.blocks.RichTextBlock(features=['link', 'ol', 'ul', 'document-link', 'image', 'embed'])), ('table_block', v1.atomic_elements.organisms.AtomicTableBlock(table_options={'renderer': 'html'})), ('tip', wagtail.wagtailcore.blocks.StructBlock([(b'content', wagtail.wagtailcore.blocks.RichTextBlock(features=[b'link', b'ol', b'ul', b'document-link', b'image', b'embed']))])), ('warning', wagtail.wagtailcore.blocks.StructBlock([(b'content', wagtail.wagtailcore.blocks.RichTextBlock(features=[b'link', b'ol', b'ul', b'document-link', b'image', b'embed']))])), ('heading', wagtail.wagtailcore.blocks.StructBlock([(b'text', v1.blocks.HeadingTextBlock(required=False)), (b'level', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'heading1', b'Heading level 1'), (b'heading2', b'Heading level 2'), (b'heading3', b'Heading level 3')]))]))], blank=True),
        ),
    ]
